### ISSUE TITLE
Error opening any topic

### ISSUE THREAD

**Issue by dragomano** [SMFTricks/Tasks-Manager#3]
I get the same error when I enter Task List and Time log areas:

'smf.tk.topic_id' isn't in GROUP BY
File: TasksManager\Tasks.php
Line: 632

MariaDB 10.6.5

**Comment by DiegoAndresCortes** [comment]
Mmm yes I just noticed a couple of bugs, might have to do a 1.1 sooner than later
This bug I presume is because I never check for projects/tasks created before doing some of the queries.
And then in addition, didn't add such columns either.
