### ISSUE TITLE
whos_online_after

### ISSUE THREAD

**Issue by live627** [SMFTricks/Tasks-Manager#6]
https://github.com/SMFTricks/Tasks-Manager/blob/793158ab00fd1685d258929b1233116df52476b1/Sources/TasksManager/Integration.php#L199-L201

whos_online_after is called by determineActions() which is called in places other than the online log  ( profile , spider log)

**Comment by DiegoAndresCortes** [comment]
I see. I guess back then I thought I was fixing the profile thing, when in reality I wanted this https://github.com/SMFTricks/ST-Shop/pull/8
Thanks
